# Generated by Django 4.0.6 on 2022-11-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=16, verbose_name='Password')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=16, verbose_name='Telefone')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
