# Generated by Django 4.0.6 on 2022-11-19 17:37

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_account_managers_account_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', main.models.UsuarioManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='criados',
        ),
        migrations.RemoveField(
            model_name='account',
            name='modificado',
        ),
        migrations.AddField(
            model_name='account',
            name='is_trusty',
            field=models.BooleanField(default=False, verbose_name='trusty'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
    ]
